<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MiShoppingShop - Trendy Clothing for Everyone</title>
    <style>
        :root {
            --primary: #ff6b6b;
            --secondary: #4ecdc4;
            --dark: #292f36;
            --light: #f7fff7;
        }
        
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            margin: 0;
            padding: 0;
            color: var(--dark);
        }
        
        header {
            background-color: white;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
            position: sticky;
            top: 0;
            z-index: 100;
        }
        
        .navbar {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 1rem 5%;
        }
        
        .logo {
            font-size: 1.8rem;
            font-weight: 700;
            color: var(--primary);
        }
        
        .nav-links {
            display: flex;
            gap: 2rem;
        }
        
        .nav-links a {
            text-decoration: none;
            color: var(--dark);
            font-weight: 500;
        }
        
        .hero {
            background: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('clothing-hero.jpg');
            background-size: cover;
            background-position: center;
            height: 70vh;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            text-align: center;
            color: white;
        }
        
        .hero h1 {
            font-size: 3.5rem;
            margin-bottom: 1rem;
        }
        
        .hero p {
            font-size: 1.2rem;
            max-width: 600px;
            margin-bottom: 2rem;
        }
        
        .btn {
            padding: 0.8rem 2rem;
            background-color: var(--primary);
            color: white;
            border: none;
            border-radius: 30px;
            font-weight: 600;
            cursor: pointer;
            transition: all 0.3s;
        }
        
        .btn:hover {
            background-color: #ff5252;
            transform: translateY(-2px);
        }
        
        .categories {
            padding: 5rem 5%;
            text-align: center;
        }
        
        .section-title {
            font-size: 2rem;
            margin-bottom: 3rem;
            position: relative;
            display: inline-block;
        }
        
        .section-title::after {
            content: '';
            position: absolute;
            bottom: -10px;
            left: 50%;
            transform: translateX(-50%);
            width: 80px;
            height: 3px;
            background-color: var(--primary);
        }
        
        .category-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
            gap: 2rem;
        }
        
        .category-card {
            position: relative;
            height: 300px;
            overflow: hidden;
            border-radius: 10px;
        }
        
        .category-card img {
            width: 100%;
            height: 100%;
            object-fit: cover;
            transition: transform 0.5s;
        }
        
        .category-card:hover img {
            transform: scale(1.05);
        }
        
        .category-overlay {
            position: absolute;
            bottom: 0;
            left: 0;
            right: 0;
            background: linear-gradient(transparent, rgba(0,0,0,0.7));
            color: white;
            padding: 1rem;
        }
        
        footer {
            background-color: var(--dark);
            color: white;
            padding: 3rem 5%;
        }
        
        .footer-content {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 2rem;
            margin-bottom: 2rem;
        }
        
        .footer-column h3 {
            font-size: 1.2rem;
            margin-bottom: 1.5rem;
            position: relative;
        }
        
        .footer-column h3::after {
            content: '';
            position: absolute;
            bottom: -8px;
            left: 0;
            width: 40px;
            height: 2px;
            background-color: var(--primary);
        }
        
        .footer-column ul {
            list-style: none;
            padding: 0;
        }
        
        .footer-column ul li {
            margin-bottom: 0.8rem;
        }
        
        .footer-column ul li a {
            color: #ddd;
            text-decoration: none;
            transition: color 0.3s;
        }
        
        .footer-column ul li a:hover {
            color: var(--primary);
        }
        
        .copyright {
            text-align: center;
            padding-top: 2rem;
            border-top: 1px solid #444;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar">
            <div class="logo">MiShoppingShop</div>
            <div class="nav-links">
                <a href="#">Home</a>
                <a href="#">Shop</a>
                <a href="#">Men</a>
                <a href="#">Women</a>
                <a href="#">Kids</a>
                <a href="#">Contact</a>
            </div>
            <div class="nav-icons">
                <a href="#"><i class="fas fa-search"></i></a>
                <a href="#"><i class="fas fa-user"></i></a>
                <a href="#"><i class="fas fa-shopping-cart"></i></a>
            </div>
        </nav>
    </header>
    
    <section class="hero">
        <h1>Summer Collection 2023</h1>
        <p>Discover our latest trends and elevate your wardrobe with premium quality clothing</p>
        <button class="btn">Shop Now</button>
    </section>
    
    <section class="categories">
        <h2 class="section-title">Shop by Category</h2>
        <div class="category-grid">
            <div class="category-card">
                <img src="men-category.jpg" alt="Men's Clothing">
                <div class="category-overlay">
                    <h3>Men's Wear</h3>
                    <button class="btn">Explore</button>
                </div>
            </div>
            <div class="category-card">
                <img src="women-category.jpg" alt="Women's Clothing">
                <div class="category-overlay">
                    <h3>Women's Wear</h3>
                    <button class="btn">Explore</button>
                </div>
            </div>
            <div class="category-card">
                <img src="kids-category.jpg" alt="Kids Clothing">
                <div class="category-overlay">
                    <h3>Kids Wear</h3>
                    <button class="btn">Explore</button>
                </div>
            </div>
            <div class="category-card">
                <img src="accessories-category.jpg" alt="Accessories">
                <div class="category-overlay">
                    <h3>Accessories</h3>
                    <button class="btn">Explore</button>
                </div>
            </div>
        </div>
    </section>
    
    <section class="featured">
        <!-- Featured products section would go here -->
    </section>
    
    <section class="newsletter">
        <!-- Newsletter signup would go here -->
    </section>
    
    <footer>
        <div class="footer-content">
            <div class="footer-column">
                <h3>MiShoppingShop</h3>
                <p>Your one-stop destination for trendy and affordable fashion for the whole family.</p>
            </div>
            <div class="footer-column">
                <h3>Quick Links</h3>
                <ul>
                    <li><a href="#">Home</a></li>
                    <li><a href="#">About Us</a></li>
                    <li><a href="#">Shop</a></li>
                    <li><a href="#">Contact</a></li>
                </ul>
            </div>
            <div class="footer-column">
                <h3>Customer Service</h3>
                <ul>
                    <li><a href="#">FAQ</a></li>
                    <li><a href="#">Shipping Policy</a></li>
                    <li><a href="#">Return Policy</a></li>
                    <li><a href="#">Privacy Policy</a></li>
                </ul>
            </div>
            <div class="footer-column">
                <h3>Contact Us</h3>
                <ul>
                    <li>123 Fashion Street, Style City</li>
                    <li>Email: info@mishoppingshop.com</li>
                    <li>Phone: +1 234 567 890</li>
                </ul>
            </div>
        </div>
        <div class="copyright">
            <p>&copy; 2023 MiShoppingShop. All Rights Reserved.</p>
        </div>
    </footer>
    
    <!-- Font Awesome for icons -->
    <script src="https://kit.fontawesome.com/a076d05399.js" crossorigin="anonymous"></script>
</body>
</html>
